### ISSUE TITLE
I hope you can provide some tutorials and examples, normal websites need to be updated frequently

### ISSUE THREAD

**Issue by yuexuan** [blimmer/cdk-wordpress-serverless#28]
Very a good idea, I hope you can provide some tutorials and examples, normal websites need to be updated frequently.Because what I want is that after the site is finished, I will close the container. The next time I need to update, I open the container again and can pick up where I left off. For example, I might install some plugins. These plugins or themes continue to work.

**Comment by blimmer** [comment]
Hello, @yuexuan. Plugins and themes should continue to work in between container restarts. The Aurora Serverless MySQL database and EFS file system are retained even if you shut down/restart your Wordpress Admin container.

In other words, you should be able to use Wordpress normally! If you discover that's not the case, please let me know.

**Comment by yuexuan** [comment]
Thank you for your reply. In the use of AWS Route 53, I encountered a very annoying problem. Every time I deleted and redeployed, I would encounter a change in the value of NS. My domain name was purchased from another website, so I had to modify it again.

Can you help with deployment optimization, if the specified domain name is detected during deployment, or the SSL certificate already exists, skip it and directly use the existing domain name and certificate instead of creating it again?



When I finished this work, when I finally created the ECS container and mounted EFS, I was unable to create it successfully. He hints: “ResourceInitializationError: failed to invoke EFS utils commands to set up EFS volumes: stderr: b'mount.nfs4: access denied by server while mounting 127.0.0.1:/' : unsuccessful EFS utils command execution; code: 32”

![image](https://github.com/blimmer/cdk-static-wordpress/assets/9717223/024ba4e5-99a8-4b1c-b99f-96b77298b015)

I am using IMA's root privileges.

**Comment by blimmer** [comment]
> In the use of AWS Route 53, I encountered a very annoying problem. Every time I deleted and redeployed, I would encounter a change in the value of NS. My domain name was purchased from another website, so I had to modify it again.

One of the goals of this project is to run the admin panel as cheaply as possible only when needed. Therefore, I don't run an application load balancer with a stable DNS entry, as this would bill even when the ECS task is not running. So, as you saw, the IP address of the container will change each time you shut down / restart.

We could consider adding a flag to run a load balancer with a more predictable DNS entry, but I would want it to default to `false` to avoid billing for that.

> Can you help with deployment optimization, if the specified domain name is detected during deployment, or the SSL certificate already exists, skip it and directly use the existing domain name and certificate instead of creating it again?

SSL is not currently supported (see #17). So I'm not exactly sure what you mean here.

> When I finished this work, when I finally created the ECS container and mounted EFS, I was unable to create it successfully. He hints: “ResourceInitializationError: failed to invoke EFS utils commands to set up EFS volumes: stderr: b'mount.nfs4: access denied by server while mounting 127.0.0.1:/' : unsuccessful EFS utils command execution; code: 32”

Hmm, it is possible that this is caused by my changes in #27. Could you try running with version [0.1.14](https://github.com/blimmer/cdk-static-wordpress/releases/tag/v0.1.14) to see if this is a new problem? To work around the circular dependency, you might need to use an older CDK version (e.g., 2.84.0) to test this.

If it's a problem, introduced by #27, I'll need to look into it to see how to fix it.

**Comment by yuexuan** [comment]
![image](https://github.com/blimmer/cdk-static-wordpress/assets/9717223/e95a63e5-fda5-4d79-b2b7-4ae3941396a6)
![image](https://github.com/blimmer/cdk-static-wordpress/assets/9717223/419b923a-0574-4d58-93c9-95774107e15a)
![image](https://github.com/blimmer/cdk-static-wordpress/assets/9717223/0e119ce7-0264-462c-b24a-0dd8dc417974)
The first problem is this, if I don't configure my dns resolution service, SSL certificate step, it will stay stuck here.

**Comment by yuexuan** [comment]
I followed your tips and tried to apply the old version. An error log occurred while the wordpress container was running.

![image](https://github.com/blimmer/cdk-static-wordpress/assets/9717223/6aafe37f-8689-43d9-804b-afc341e58f5a)


I am very much looking forward to you providing a new version to fix these issues. It's a really good idea.Thanks very much!

**Comment by blimmer** [comment]
> The first problem is this, if I don't configure my dns resolution service, SSL certificate step, it will stay stuck here.

Ah, OK, I understand now. While we don't provide SSL support for the admin container, you're correct that I do set up SSL automatically for the static version of the site. I currently do not have an option to disable SSL for the CloudFront stack: https://github.com/blimmer/cdk-static-wordpress/blob/8abc6fff1df3b7b0c94368615ad77682393ff7dd/src/StaticHosting.ts#L54-L58

This package assumes you're using a Route53 hosted zone to manage your DNS in AWS. I don't intend to change that behavior. If your main DNS nameservers are hosted elsewhere, you can always delegate a subdomain to AWS Route 53: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/CreatingNewSubdomain.html

> An error log occurred while the wordpress container was running.

Thank you for bringing this to my attention. I was able to reproduce the error you encountered and released a fix in 0.1.16: https://github.com/blimmer/cdk-static-wordpress/releases/tag/v0.1.16

If you encounter additional issues, please open a new GitHub issue. Thanks!
